In [1]:
import pandas as pd

df = pd.read_csv('../data/processed/clustered_data_diabetes.csv')
df.head()
df.info()
# df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    float64
 1   Glucose                   768 non-null    float64
 2   BloodPressure             768 non-null    float64
 3   SkinThickness             768 non-null    float64
 4   Insulin                   768 non-null    float64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    float64
 8   Cluster                   768 non-null    int64
dtypes: float64(8), int64(1)
memory usage: 54.1 KB

In [ ]:
class1 = df[df['Cluster'] == 0]
class2 = df[df['Cluster'] == 1]

In [ ]:
class1.info()
class1.describe()

<class 'pandas.DataFrame'>
Index: 223 entries, 4 to 764
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               223 non-null    float64
 1   Glucose                   223 non-null    float64
 2   BloodPressure             223 non-null    float64
 3   SkinThickness             223 non-null    float64
 4   Insulin                   223 non-null    float64
 5   BMI                       223 non-null    float64
 6   DiabetesPedigreeFunction  223 non-null    float64
 7   Age                       223 non-null    float64
 8   Cluster                   223 non-null    int64
dtypes: float64(8), int64(1)
memory usage: 17.4 KB

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Cluster
count,223.000000,223.000000,223.000000,223.000000,223.000000,223.000000,223.000000,223.000000,223.0
mean,2.022422,133.162930,74.260090,36.104634,189.854634,38.185874,0.526686,28.403587,0.0
std,1.932286,28.934116,11.883743,7.601105,81.702835,5.459500,0.307800,6.312321,0.0
min,0.000000,67.000000,40.000000,13.000000,14.000000,22.900000,0.088000,21.000000,0.0
25%,0.000000,112.000000,66.666667,31.000000,134.166667,34.300000,0.266500,24.000000,0.0
50%,1.000000,128.000000,76.000000,36.000000,178.000000,37.700000,0.433000,27.000000,0.0
75%,3.000000,152.000000,82.000000,41.000000,242.833333,42.250000,0.706500,31.000000,0.0
max,7.000000,199.000000,104.000000,57.000000,360.625000,50.250000,1.200000,58.000000,0.0

In [ ]:
class2.info()
class2.describe()

<class 'pandas.DataFrame'>
Index: 228 entries, 0 to 763
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               228 non-null    float64
 1   Glucose                   228 non-null    float64
 2   BloodPressure             228 non-null    float64
 3   SkinThickness             228 non-null    float64
 4   Insulin                   228 non-null    float64
 5   BMI                       228 non-null    float64
 6   DiabetesPedigreeFunction  228 non-null    float64
 7   Age                       228 non-null    float64
 8   Cluster                   228 non-null    int64
dtypes: float64(8), int64(1)
memory usage: 17.8 KB

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Cluster
count,228.000000,228.000000,228.000000,228.000000,228.000000,228.000000,228.000000,228.000000,228.0
mean,7.491228,135.241228,78.039474,31.131579,170.841923,32.692909,0.464855,47.017544,1.0
std,3.022662,30.531686,10.489904,7.477638,68.516474,5.775790,0.294116,9.510933,0.0
min,0.000000,57.000000,50.000000,7.000000,29.000000,19.600000,0.085000,29.000000,1.0
25%,5.750000,111.000000,72.000000,27.000000,124.666667,28.475000,0.244000,40.000000,1.0
50%,8.000000,133.000000,78.000000,31.000000,158.833333,32.800000,0.376000,45.000000,1.0
75%,9.250000,158.000000,84.000000,35.666667,207.218750,35.925000,0.654000,54.000000,1.0
max,13.500000,197.000000,104.000000,57.000000,360.625000,50.250000,1.200000,66.500000,1.0

<class 'pandas.DataFrame'>
Index: 317 entries, 1 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               317 non-null    float64
 1   Glucose                   317 non-null    float64
 2   BloodPressure             317 non-null    float64
 3   SkinThickness             317 non-null    float64
 4   Insulin                   317 non-null    float64
 5   BMI                       317 non-null    float64
 6   DiabetesPedigreeFunction  317 non-null    float64
 7   Age                       317 non-null    float64
 8   Cluster                   317 non-null    int64
dtypes: float64(8), int64(1)
memory usage: 24.8 KB

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Cluster
count,317.000000,317.00000,317.000000,317.000000,317.000000,317.000000,317.000000,317.000000,317.0
mean,2.485804,103.60673,66.837014,22.601472,95.008149,28.044427,0.406965,26.635647,2.0
std,2.041644,21.24180,10.218761,6.769977,49.302824,4.565315,0.251601,6.165740,0.0
min,0.000000,44.00000,40.000000,8.000000,15.000000,18.200000,0.078000,21.000000,2.0
25%,1.000000,89.00000,60.000000,18.000000,61.333333,24.700000,0.223000,22.000000,2.0
50%,2.000000,100.00000,66.000000,22.333333,84.000000,27.800000,0.336000,25.000000,2.0
75%,4.000000,115.00000,74.000000,28.000000,116.000000,31.200000,0.529000,29.000000,2.0
max,10.000000,191.00000,104.000000,41.000000,360.625000,39.500000,1.200000,66.500000,2.0